version: '3.8'

services:
  api:
    container_name: sgtbot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/user/sgtbot'
    env_file:
      - '.env'
    ports:
      - '${PORT}:${PORT}'
    command: sh -c 'chmod +x /home/user/sgtbot/entrypoint.sh && /home/user/sgtbot/entrypoint.sh && python run.py'
  
  worker:
    container_name: sgtbot-worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/user/sgtbot'
    env_file:
      - '.env'
    depends_on:
      - redis
    command: celery -A run.celery_app worker -l info

  redis:
    container_name: sgtbot-redis
    image: redis:7.0.2-alpine
    volumes:
      - 'redis:/data'

volumes:
  redis: